apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ivan
  namespace: projectx
subjects:
- kind: User
  name: ivan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: all-role
  apiGroup: rbac.authorization.k8s.io
