apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: all-role
  namespace: projectx
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - "apps"
  resources:
  - replicasets
  verbs:
  - get
  - list
  - create
  - delete
