apiVersion: apps/v1
kind: Deployment
metadata:
  name: appa-deploy
  annotations:
    kubernetes.io/change-cause: "Update to v3"
spec:
  replicas: 15
  selector:
    matchLabels: 
      app: appa
      ver: v1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 5
      maxSurge: 1
  template:
    metadata:
      labels:
        app: appa
        ver: v1
    spec:
      containers:
      - name: appa-container
        image: shekeriev/k8s-appa:v3
        ports:
        - containerPort: 80 
