apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deploy
  namespace: projectx
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: consumer-app
      role: consumer
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: consumer-app
        role: consumer
    spec:
      containers:
      - name: cons-container
        image: shekeriev/k8s-consumer:latest
        ports:
        - containerPort: 5000
