apiVersion: v1
kind: Namespace
metadata:
  name: homework
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    purpose: homework
  labels:
    app: hw
  name: homework-1
  namespace: homework
spec:
  containers:
  - image: shekeriev/k8s-oracle
    name: homework-1
---
apiVersion: v1
kind: Pod
metadata:
  annotations:
    purpose: homework
  labels:
    app: hw
  name: homework-2
  namespace: homework
spec:
  containers:
  - image: shekeriev/k8s-oracle
    name: homework-2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hw
  name: homework-svc
  namespace: homework
spec:
  ports:
  - name: 5000-5000
    nodePort: 32000
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: hw
  type: NodePort